--- 
- name: Temperature
  uuid: 1fd25c46-4163-11de-aad1-001ff3caa767
  port: 0
  period: 0.1
  max: 40.0
  id: 1
  display_precision: -1
  unit: degC
  min: 0.0
  step_size: 0.1
  ptype: 0
- name: Light
  uuid: 202233ce-4163-11de-aad1-001ff3caa767
  port: 0
  period: 0.1
  max: 4000.0
  id: 2
  display_precision: 0
  unit: lux
  min: 0.0
  step_size: 0.1
  ptype: 2
- name: Pressure
  uuid: 2022efee-4163-11de-aad1-001ff3caa767
  port: 0
  period: 0.1
  max: 104.0
  id: 3
  display_precision: -1
  unit: kPa
  min: 96.0
  step_size: 0.1
  ptype: 3
- name: Voltage
  uuid: 2023bdb6-4163-11de-aad1-001ff3caa767
  port: 0
  period: 0.1
  max: 10.0
  id: 4
  display_precision: -2
  unit: V
  min: -10.0
  step_size: 0.1
  ptype: 4
- name: Force (5N)
  uuid: 20263140-4163-11de-aad1-001ff3caa767
  port: 0
  period: 0.01
  max: 4.0
  id: 5
  display_precision: -2
  unit: N
  min: -4.0
  step_size: 0.01
  ptype: 5
- name: Force (50N)
  uuid: 2026e04a-4163-11de-aad1-001ff3caa767
  port: 0
  period: 0.01
  max: 40.0
  id: 6
  display_precision: -1
  unit: N
  min: -40.0
  step_size: 0.1
  ptype: 5
- name: Position
  uuid: 20276f7e-4163-11de-aad1-001ff3caa767
  port: 0
  period: 0.1
  max: 4.0
  id: 7
  display_precision: -2
  unit: m
  min: 0.0
  step_size: 0.1
  ptype: 13
- name: Relative Humidity
  uuid: 2027e9ea-4163-11de-aad1-001ff3caa767
  port: 0
  period: 0.1
  max: 90.0
  id: 8
  display_precision: -1
  unit: percentage
  min: 10.0
  step_size: 0.1
  ptype: 7
- name: CO2
  uuid: 20286398-4163-11de-aad1-001ff3caa767
  port: 0
  period: 1.0
  max: 500.0
  id: 9
  display_precision: 2
  unit: ppm
  min: 0.0
  step_size: 20.0
  ptype: 18
- name: pH
  uuid: 20295af0-4163-11de-aad1-001ff3caa767
  port: 0
  period: 0.1
  max: 14.0
  id: 11
  display_precision: -1
  unit: pH
  min: 0.0
  step_size: 0.1
  ptype: 20
- name: Salinity
  uuid: 202a39de-4163-11de-aad1-001ff3caa767
  port: 0
  period: 0.1
  max: 50.0
  id: 12
  display_precision: -1
  unit: ppt
  min: 0.0
  step_size: 0.1
  ptype: 21
- name: Raw Data
  uuid: 202adb78-4163-11de-aad1-001ff3caa767
  port: 0
  period: 0.1
  max: 10000.0
  id: 13
  display_precision: 0
  unit: raw
  min: -10000.0
  step_size: 1.0
  ptype: 22
- name: Raw Voltage
  uuid: 202b81fe-4163-11de-aad1-001ff3caa767
  port: 0
  period: 0.1
  max: 10.0
  id: 14
  display_precision: -2
  unit: V
  min: -1.0
  step_size: 0.01
  ptype: 23
- name: Sound Level
  uuid: 202c226c-4163-11de-aad1-001ff3caa767
  port: 0
  period: 0.1
  max: 120.0
  id: 15
  display_precision: -1
  unit: dB
  min: 0.0
  step_size: 1.0
  ptype: 14
- name: Magnetic Field
  uuid: 202ca3ea-4163-11de-aad1-001ff3caa767
  port: 0
  period: 0.1
  max: 10.0
  id: 16
  display_precision: -1
  unit: G
  min: 0.0
  step_size: 0.1
  ptype: 26
- name: EKG
  uuid: f1eeba28-7b7a-11e0-9cce-9027e4e96711
  port: 0
  period: 0.01
  max: 4.0
  id: 17
  display_precision: -1
  unit: mV
  min: -0.5
  step_size: 0.1
  ptype: 29
- name: "Current (+/- 0.6A) "
  uuid: d6dbaafa-856d-11e0-9af0-9027e4e96711
  port: 0
  period: 0.1
  max: 0.6
  id: 18
  display_precision: -3
  unit: A
  min: -0.6
  step_size: 0.001
  ptype: 10
- name: Current (+/- 10A)
  uuid: 928fa274-856e-11e0-9af0-9027e4e96711
  port: 0
  period: 0.1
  max: 10.0
  id: 19
  display_precision: -2
  unit: A
  min: -10.0
  step_size: 0.01
  ptype: 10
- name: UVA Intensity
  uuid: f847e838-856e-11e0-9af0-9027e4e96711
  port: 0
  period: 0.1
  max: 0.0
  id: 20
  display_precision: 0
  unit: mW/m^2
  min: 20000.0
  step_size: 10.0
  ptype: 35
- name: UVB Intensity
  uuid: f5274ab6-8570-11e0-9af0-9027e4e96711
  port: 0
  period: 0.1
  max: 1000.0
  id: 21
  display_precision: 0
  unit: mW/m^2
  min: 0.0
  step_size: 1.0
  ptype: 36
