--- 
- name: Temperature
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: degC
  max: 40.0
  uuid: 1fd25c46-4163-11de-aad1-001ff3caa767
  port: 0
  id: 1
  display_precision: -1
  min: 0.0
  user_id: 9
  step_size: 0.1
  ptype: 0
  created_at: 2009-05-15 13:20:30 Z
- name: Light
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: lux
  max: 4000.0
  uuid: 202233ce-4163-11de-aad1-001ff3caa767
  port: 0
  id: 2
  display_precision: 0
  min: 0.0
  user_id: 9
  step_size: 0.1
  ptype: 2
  created_at: 2009-05-15 13:20:30 Z
- name: Pressure
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: kPa
  max: 104.0
  uuid: 2022efee-4163-11de-aad1-001ff3caa767
  port: 0
  id: 3
  display_precision: -1
  min: 96.0
  user_id: 9
  step_size: 0.1
  ptype: 3
  created_at: 2009-05-15 13:20:30 Z
- name: Voltage
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: V
  max: 10.0
  uuid: 2023bdb6-4163-11de-aad1-001ff3caa767
  port: 0
  id: 4
  display_precision: -2
  min: -10.0
  user_id: 9
  step_size: 0.1
  ptype: 4
  created_at: 2009-05-15 13:20:30 Z
- name: Force (5N)
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.01
  unit: N
  max: 4.0
  uuid: 20263140-4163-11de-aad1-001ff3caa767
  port: 0
  id: 5
  display_precision: -2
  min: -4.0
  user_id: 9
  step_size: 0.01
  ptype: 5
  created_at: 2009-05-15 13:20:30 Z
- name: Force (50N)
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.01
  unit: N
  max: 40.0
  uuid: 2026e04a-4163-11de-aad1-001ff3caa767
  port: 0
  id: 6
  display_precision: -1
  min: -40.0
  user_id: 9
  step_size: 0.1
  ptype: 5
  created_at: 2009-05-15 13:20:30 Z
- name: Position
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: m
  max: 4.0
  uuid: 20276f7e-4163-11de-aad1-001ff3caa767
  port: 0
  id: 7
  display_precision: -2
  min: 0.0
  user_id: 9
  step_size: 0.1
  ptype: 13
  created_at: 2009-05-15 13:20:30 Z
- name: Relative Humidity
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: percentage
  max: 90.0
  uuid: 2027e9ea-4163-11de-aad1-001ff3caa767
  port: 0
  id: 8
  display_precision: -1
  min: 10.0
  user_id: 9
  step_size: 0.1
  ptype: 7
  created_at: 2009-05-15 13:20:30 Z
- name: CO2
  uuid: 20286398-4163-11de-aad1-001ff3caa767
  port: 0
  period: 1.0
  max: 500.0
  id: 9
  display_precision: 2
  user_id: 5
  unit: ppm
  min: 0.0
  step_size: 20.0
  ptype: 18
- name: pH
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: pH
  max: 14.0
  uuid: 20295af0-4163-11de-aad1-001ff3caa767
  port: 0
  id: 11
  display_precision: -1
  min: 0.0
  user_id: 9
  step_size: 0.1
  ptype: 20
  created_at: 2009-05-15 13:20:30 Z
- name: Salinity
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: ppt
  max: 50.0
  uuid: 202a39de-4163-11de-aad1-001ff3caa767
  port: 0
  id: 12
  display_precision: -1
  min: 0.0
  user_id: 9
  step_size: 0.1
  ptype: 21
  created_at: 2009-05-15 13:20:30 Z
- name: Raw Data
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: raw
  max: 10000.0
  uuid: 202adb78-4163-11de-aad1-001ff3caa767
  port: 0
  id: 13
  display_precision: 0
  min: -10000.0
  user_id: 9
  step_size: 1.0
  ptype: 22
  created_at: 2009-05-15 13:20:30 Z
- name: Raw Voltage
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: V
  max: 10.0
  uuid: 202b81fe-4163-11de-aad1-001ff3caa767
  port: 0
  id: 14
  display_precision: -2
  min: -1.0
  user_id: 9
  step_size: 0.01
  ptype: 23
  created_at: 2009-05-15 13:20:30 Z
- name: Sound Level
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: dB
  max: 120.0
  uuid: 202c226c-4163-11de-aad1-001ff3caa767
  port: 0
  id: 15
  display_precision: -1
  min: 0.0
  user_id: 9
  step_size: 1.0
  ptype: 14
  created_at: 2009-05-15 13:20:30 Z
- name: Magnetic Field
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: G
  max: 10.0
  uuid: 202ca3ea-4163-11de-aad1-001ff3caa767
  port: 0
  id: 16
  display_precision: -1
  min: 0.0
  user_id: 9
  step_size: 0.1
  ptype: 26
  created_at: 2009-05-15 13:20:30 Z
