production:
  password_for_default_users: ccpassword
  site_name: <%= ENV["SITE_NAME"] %>
  site_url: <%= ENV["SITE_URL"] %>
  authoring_site_url: <%= ENV["AUTHORING_SITE_URL"] %>
  theme: <%= ENV["THEME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  help_email: <%= ENV["HELP_EMAIL"] %>
  default_maven_jnlp:
    server: concord
    family: all-otrunk-snapshot
    version: snapshot
  maven_jnlp_families:
  - all-otrunk-snapshot
  maven_jnlp_servers:
  - name: concord
    host: http://jnlp.concord.org
    path: /dev3/org/concord/maven-jnlp/
  use_adhoc_workgroups: true
  site_school: <%= ENV["SITE_NAME"] %>-school
  site_district: <%= ENV["SITE_NAME"] %>-district
  use_gse: false
  active_school_levels:
  - '2'
  - '3'
  - '4'
  active_grades:
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  net_logo_package_name: otrunknl41
  tiny_mce:
    buttons1:
    - bold,italic,underline
    - sup,sub
    - bullist,numlist
    - link,image
    - pastext, pasteword,selectall
    - code
  dont_sanitize_xhtml: false
  default_admin_user:
    first_name: Noah
    login: knowuh
    last_name: Paessel
  email: npaessel@concord.org
  states_and_provinces: all
  runnables_use: otrunk_jnlp
  runnable_mime_type:
  top_level_container_name: <%= ENV["TOP_LEVEL_CONTAINER_NAME"] %>
  pepper: <%= ENV["SITE_KEY"] %>
  codap_url: http://codap.concord.org/releases/latest/
  log_manager_data_interactive_url: //cc-log-manager.herokuapp.com/di
