---
javascripts:
- base:
  - effects
  - dragdrop
  - controls
  - misc/resizable
  - flotr/excanvas
  - flotr/flotr
  - canvas2image
  - application
  - dropdown
  - cookie
  - accordion
  - item_selectable
  - live_validation
  - please_wait
  - report_filter
  - pagination
  - workgroup
  - chosen.proto
  - pt_event_simulate
  - prototype-ui/prototype-ui
stylesheets:
- print:
  - print
- base:
  - app
  - accordion
  - window/window
  - window/rites
  - window/lightbox
  - live_validation
  - action_menu_tab
  - notes
  - drop_down
  - data_table
  - reports
  - workgroup
  - chosen
  - site_notice
- default:
  - app
  - accordion
  - window/window
  - window/rites
  - window/lightbox
  - live_validation
  - action_menu_tab
  - notes
  - drop_down
  - data_table
  - reports
  - chosen

- has:
  - app
  - accordion
  - please_wait
  - window/window
  - window/rites
  - window/lightbox
  - live_validation
  - action_menu_tab
  - notes
  - drop_down
  - data_table
  - reports
  - workgroup
  - chosen
  - classes_left_pane
  - instructional_materials
  - site_notice
  - search_materials

- xproject:
  - app
  - accordion
  - please_wait
  - window/window
  - window/rites
  - window/lightbox
  - live_validation
  - action_menu_tab
  - notes
  - drop_down
  - data_table
  - reports
  - workgroup
  - chosen
  - classes_left_pane
  - instructional_materials
  - site_notice
  - search_materials
