--- 
javascripts: 
- base: 
  - effects
  - dragdrop
  - controls
  - misc/resizable
  - flotr/excanvas
  - flotr/flotr
  - canvas2image
  - application
  - dropdown
  - cookie
  - accordion
  - item_selectable
  - live_validation
  - please_wait
  - report_filter
  - template_toggle 
  - unit_bins
  - pagination
  - workgroup
  - chosen.proto
  - pt_event_simulate  
stylesheets: 
- base: 
  - app
  - authoring
  - template_edit
  - accordion
  - window/window
  - window/rites
  - live_validation
  - action_menu_tab
  - notes
  - drop_down
  - data_table
  - reports
  - workgroup
  - chosen

- default:
  - app
  - authoring
  - template_edit
  - accordion
  - window/window
  - window/rites
  - live_validation
  - action_menu_tab
  - notes
  - drop_down
  - data_table
  - reports
  - chosen
  
- rites:
  - app
  - authoring
  - accordion
  - please_wait
  - window/window
  - window/rites
  - live_validation
  - accordion
  - notes
  - action_menu_tab
  - drop_down
  - data_table
  - reports
  - workgroup
  - chosen 
- investigations:
  - themes/investigations/investigations
  - themes/investigations/action_menu_tab
  - themes/investigations/drop_down
  - themes/investigations/accordion
  - window/window
  - window/rites
  - live_validation
  - notes
  - data_table
  - reports

- itsisu:
  - app
  - authoring
  - template_edit
  - accordion
  - window/window
  - window/rites
  - action_menu_tab
  - notes
  - drop_down
  - data_table
  - reports
  - bin
  - chosen

- smartgraphs:
  - app
  - accordion
  - window/window
  - window/rites
  - live_validation
  - action_menu_tab
  - notes
  - drop_down
  - data_table
  - reports

- sglight:
  - themes/sglight/sglight
  - themes/sglight/action_menu_tab
  - themes/sglight/drop_down
  - themes/sglight/accordion
  - window/window
  - window/rites
  - live_validation
  - notes
  - data_table
  - reports

- sparks:
  - app
  - accordion
  - please_wait
  - window/window
  - window/rites
  - live_validation
  - accordion
  - notes
  - action_menu_tab
  - drop_down
  - data_table
  - reports
  - chosen

- has:
  - app
  - accordion
  - please_wait
  - live_validation
  - accordion
  - notes
  - action_menu_tab
  - drop_down
  - data_table
  - reports
  - workgroup
  - chosen

- xproject:
  - app
  - accordion
  - window/window
  - window/rites
  - live_validation
  - action_menu_tab
  - notes
  - drop_down
  - data_table
  - reports
  - chosen

- genomedynamics:
  - app
  - accordion
  - window/window
  - window/rites
  - live_validation
  - action_menu_tab
  - notes
  - drop_down
  - data_table
  - reports
  - themes/genomedynamics/genomedynamics
  
- geniverse:
  - app
  - accordion
  - window/window
  - window/rites
  - live_validation
  - accordion
  - notes
  - action_menu_tab
  - drop_down
  - data_table
  - reports
  - themes/geniverse/geniverse
  - themes/geniverse/action_menu_tab
  - themes/geniverse/drop_down
  - themes/geniverse/accordion

