--- 
javascripts: 
- base: 
  - prototype
  - prototype-ui/prototype-ui
  - effects
  - dragdrop
  - controls
  - scriptaculous
  - misc/resizable
  - livepipe/livepipe
  - livepipe/window
  - flotr/excanvas
  - flotr/flotr
  - canvas2image
  - application
  - dropdown
  - cookie
  - accordion
  - item_selectable
  - live_validation
  - please_wait
  - report_filter
  
stylesheets: 
- base: 
  - app
  - accordion
  - window/window
  - window/rites
  - live_validation
  - action_menu_tab
  - notes
  - drop_down
  - data_table
  - reports

- default:
  - app
  - accordion
  - window/window
  - window/rites
  - live_validation
  - action_menu_tab
  - notes
  - drop_down
  - data_table
  - reports
  
- rites:
  - app
  - accordion
  - please_wait
  - window/window
  - window/rites
  - live_validation
  - accordion
  - notes
  - action_menu_tab
  - drop_down
  - data_table
  - reports
  - themes/rites/rites
  
- investigations:
  - themes/investigations/investigations
  - themes/investigations/action_menu_tab
  - themes/investigations/drop_down
  - themes/investigations/accordion
  - window/window
  - window/rites
  - live_validation
  - notes
  - data_table
  - reports

- itsisu:
  - themes/itsisu/itsisu
  - themes/itsisu/action_menu_tab
  - themes/itsisu/drop_down
  - themes/itsisu/accordion
  - window/window
  - window/itsisu
  - live_validation
  - notes
  - data_table
  - reports

- smartgraphs:
  - themes/smartgraphs/smartgraphs
  - themes/smartgraphs/action_menu_tab
  - themes/smartgraphs/drop_down
  - themes/smartgraphs/accordion
  - window/window
  - window/rites
  - live_validation
  - notes
  - data_table
  - reports

- sglight:
  - themes/sglight/sglight
  - themes/sglight/action_menu_tab
  - themes/sglight/drop_down
  - themes/sglight/accordion
  - window/window
  - window/rites
  - live_validation
  - notes
  - data_table
  - reports

- sparks:
  - app
  - accordion
  - please_wait
  - window/window
  - window/rites
  - live_validation
  - accordion
  - notes
  - action_menu_tab
  - drop_down
  - data_table
  - reports

- has:
  - themes/has/has
  - themes/has/action_menu_tab
  - themes/has/drop_down
  - themes/has/accordion
  - window/window
  - window/rites
  - live_validation
  - notes
  - data_table
  - reports

- xproject:
  - app
  - accordion
  - window/window
  - window/rites
  - live_validation
  - action_menu_tab
  - notes
  - drop_down
  - data_table
  - reports

- genomedynamics:
  - app
  - accordion
  - window/window
  - window/rites
  - live_validation
  - action_menu_tab
  - notes
  - drop_down
  - data_table
  - reports
  - themes/genomedynamics/genomedynamics
  
- geniverse:
  - app
  - accordion
  - window/window
  - window/rites
  - live_validation
  - accordion
  - notes
  - action_menu_tab
  - drop_down
  - data_table
  - reports
  - themes/geniverse/geniverse
  - themes/geniverse/action_menu_tab
  - themes/geniverse/drop_down
  - themes/geniverse/accordion

