<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_format = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} "
std_opts = " --strict --tags ~@wip"
%>
default: --drb <%= std_format %> <%= std_opts %> features
wip: --drb --tags @wip:3 --wip features
rerun: --drb <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
textmate: --drb --format html <%= std_opts %> features
