--- 
development: 
  encoding: utf8
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  username: root
  database: rites_development
  password: *****
  pool: 5

test: &test_settings
  encoding: utf8
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  username: root
  database: rites_test
  password: *****
  pool: 5

cucumber:
  <<: *test_settings

staging: 
  encoding: utf8
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  username: root
  database: rites_staging
  password: 
  pool: 5

production: 
  encoding: utf8
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  username: root
  reconnect: true
  database: rites_production
  password: *****
  pool: 5

# Optionally used for importing of ITSI activities
itsi: 
  encoding: utf8
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  username: root
  database: production_itsi_prod
  password: *****
  pool: 5
  asset_url: http://itsidiy.concord.org

# Optionally used with the itsi database for importing ITSI units
ccportal:
  encoding: utf8
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  username: root
  database: ccportal
  password: *****
  pool: 5
