development: &non_production_settings
  :password_for_default_users: secret
  :site_name: Rails Portal (development)
  :site_url: http://localhost:3000
  :authoring_site_url: //authoring.staging.concord.org
  :codap_url: http://codap.concord.org/releases/latest/
  :log_manager_data_interactive_url: //cc-log-manager.herokuapp.com/di
  :description: ""
  :default_admin_user: &default_admin_user
    :login: stephen
    :email: stephen.bannasch@gmail.com
    :first_name: Stephen
    :last_name: Bannasch
  :include_otrunk_examples: false
  :site_district: Rails Portal-district
  :site_school: Rails Portal-school
  :states_and_provinces: &states_and_provinces
    - MA
  :active_school_levels: &active_school_levels
    - "2"
    - "3"
    - "4"
  :active_grades: &active_grades
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
  :active_grades: *active_grades
  :theme: default
  :help_email: rails-portal@concord.org
  :dont_sanitize_xhtml: true
  :tiny_mce:
    :buttons1:
      - bold,italic,underline
      - formatselect
      - styleselect
      - sup,sub
      - bullist,numlist
      - link,image
      - pastext, pasteword,selectall
      - justifyleft,justifycenter,justifyright
      - code
  :pepper: 7ed5d246-cc1a-11e1-81dd-0800270eb79b
  :password_for_default_users: password
  :use_gse: false

test:
  <<: *non_production_settings
  :password_for_default_users: password

cucumber:
  <<: *non_production_settings
  :password_for_default_users: password

staging:
  :password_for_default_users: secret
  :site_name: Rails Portal (staging)
  :authoring_site_url: //authoring.staging.concord.org
  :codap_url: http://codap.concord.org/releases/latest/
  :log_manager_data_interactive_url: //cc-log-manager.herokuapp.com/di
  :site_url: http://rails-portal.staging.concord.org
  :description: ""
  :default_admin_user: *default_admin_user
  :include_otrunk_examples: false
  :states_and_provinces: *states_and_provinces
  :active_school_levels: *active_school_levels
  :active_grades: *active_grades
  :site_district: Rails Portal-district
  :site_school: Rails Portal-school
  :help_email: rails-portal@concord.org
  :dont_sanitize_xhtml: true
  :tiny_mce:
    :buttons1:
      - bold,italic,underline
      - sup,sub
      - bullist,numlist
      - link,image
      - pastext, pasteword,selectall
      - justifyleft,justifycenter,justifyright
      - code
  :pepper: 7ed5d246-cc1a-11e1-81dd-0800270eb79b

production:
  :site_name: Rails Portal
  :site_url: http://rails-portal.concord.org
  :authoring_site_url: //authoring.staging.concord.org
  :codap_url: http://codap.concord.org/releases/latest/
  :log_manager_data_interactive_url: //cc-log-manager.herokuapp.com/di
  :description: ""
  :default_admin_user: *default_admin_user
  :include_otrunk_examples: false
  :states_and_provinces: *states_and_provinces
  :active_school_levels: *active_school_levels
  :active_grades: *active_grades
  :site_district: Rails Portal-district
  :site_school: Rails Portal-school
  :help_email: rails-portal@concord.org
  :admin_email: npaessel@concord.org
  :allow_drafts_in_assignments: false
  :dont_sanitize_xhtml: true
  :tiny_mce:
    :buttons1:
      - bold,italic,underline
      - sup,sub
      - bullist,numlist
      - link,image
      - pastext, pasteword,selectall
      - justifyleft,justifycenter,justifyright
      - code
  :pepper: 7ed5d246-cc1a-11e1-81dd-0800270eb79b
