---
development: &id003
  :active_school_levels:
    - "2"
    - "3"
    - "4"
  :active_grades:
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
  :theme: has
  :site_name: HAS Investigations
  :site_url: http://has.portal.concord.org
  :runnables_use: otrunk_jnlp
  :runnable_mime_type:
  :top_level_container_name: investigation
  :site_school: HAS Investigations-school
  :description: ""
  :site_district: HAS Investigations-district
  :help_email: apallant@concord.org
  :use_gse: false
  :enable_default_users: true
  :admin_email: aunger@concord.org
  :tiny_mce:
    :buttons1:
    - bold,italic,underline
    - sup,sub
    - bullist,numlist
    - link,image
    - pastext, pasteword,selectall
    - justifyleft,justifycenter,justifyright
    - code

  :default_admin_user:
    :first_name: Aaron
    :login: aunger
    :last_name: Unger
    :email: aunger@concord.org
  :states_and_provinces:
    - MA
  :maven_jnlp_servers:
    - :name: concord
      :host: http://jnlp.concord.org
      :path: /dev/org/concord/maven-jnlp/
  :maven_jnlp_families:
    - has-otrunk
  :default_maven_jnlp:
    :version: 0.1.0-20100824.215501
    :server: concord
    :family: has-otrunk
  :valid_sakai_instances:

test: *id003
production: *id003
staging: *id003
cucumber: *id003
